// Dados de exemplo para o sistema
import type {
  Produto,
  Servico,
  Cliente,
  Funcionario,
  Venda,
  Caixa,
  CategoriaDespesa,
  ContaPagar,
  ContaReceber,
  VendaPrazo,
  Perda, // Importando tipo Perda
  CategoriaPerda, // Importando novo tipo CategoriaPerda
} from "./types"

export const produtosMock: Produto[] = [
  {
    id: "1",
    nome: "Cópia de Chave Simples",
    codigo: "CHAVE-001",
    preco: 15.0,
    custoUnitario: 5.0,
    estoque: 150,
    categoria: "Chaves",
    descricao: "Cópia de chave residencial padrão",
    ativo: true,
  },
  {
    id: "2",
    nome: "Cópia de Chave Tetra",
    codigo: "CHAVE-002",
    preco: 25.0,
    custoUnitario: 10.0,
    estoque: 80,
    categoria: "Chaves",
    descricao: "Cópia de chave tetra canalhão",
    ativo: true,
  },
  {
    id: "3",
    nome: "Controle Remoto Universal",
    codigo: "CONTR-001",
    preco: 80.0,
    custoUnitario: 40.0,
    estoque: 25,
    categoria: "Controles",
    descricao: "Controle remoto para portão",
    ativo: true,
  },
  {
    id: "4",
    nome: "Chave Codificada",
    codigo: "CHAVE-003",
    preco: 45.0,
    custoUnitario: 20.0,
    estoque: 50,
    categoria: "Chaves",
    descricao: "Chave com código de segurança",
    ativo: true,
  },
  {
    id: "5",
    nome: "Cadeado 40mm",
    codigo: "CAD-001",
    preco: 35.0,
    custoUnitario: 18.0,
    estoque: 40,
    categoria: "Cadeados",
    ativo: true,
  },
]

export const servicosMock: Servico[] = [
  {
    id: "1",
    nome: "Abertura de Porta",
    codigo: "SERV-001",
    preco: 120.0,
    duracao: 30,
    categoria: "Chaveiro",
    descricao: "Serviço de abertura de porta trancada",
    ativo: true,
  },
  {
    id: "2",
    nome: "Instalação de Fechadura",
    codigo: "SERV-002",
    preco: 150.0,
    duracao: 60,
    categoria: "Chaveiro",
    descricao: "Instalação de fechadura completa",
    ativo: true,
  },
  {
    id: "3",
    nome: "Programação de Controle",
    codigo: "SERV-003",
    preco: 50.0,
    duracao: 15,
    categoria: "Eletrônica",
    descricao: "Programação de controle remoto",
    ativo: true,
  },
  {
    id: "4",
    nome: "Manutenção de Fechadura",
    codigo: "SERV-004",
    preco: 80.0,
    duracao: 45,
    categoria: "Chaveiro",
    descricao: "Manutenção de fechadura",
    ativo: true,
  },
]

export const clientesMock: Cliente[] = [
  {
    id: "1",
    nome: "João Silva",
    email: "joao.silva@email.com",
    telefone: "(11) 98765-4321",
    cpf: "123.456.789-00",
    dataCadastro: "2024-01-15",
    ultimaCompra: "2024-11-10",
  },
  {
    id: "2",
    nome: "Maria Santos",
    email: "maria.santos@email.com",
    telefone: "(11) 97654-3210",
    dataCadastro: "2024-02-20",
    ultimaCompra: "2024-11-11",
  },
  {
    id: "3",
    nome: "Carlos Oliveira",
    telefone: "(11) 96543-2109",
    dataCadastro: "2024-03-10",
    ultimaCompra: "2024-11-08",
  },
]

export const funcionariosMock: Funcionario[] = [
  {
    id: "1",
    nome: "Roberto Souza",
    email: "roberto@chavesmart.com",
    telefone: "(11) 95432-1098",
    cargo: "Gerente",
    salario: 3500.0,
    dataAdmissao: "2023-01-10",
    ativo: true,
  },
  {
    id: "2",
    nome: "Ana Costa",
    email: "ana@chavesmart.com",
    telefone: "(11) 94321-0987",
    cargo: "Atendente",
    salario: 2000.0,
    dataAdmissao: "2023-06-15",
    ativo: true,
  },
  {
    id: "3",
    nome: "Pedro Lima",
    email: "pedro@chavesmart.com",
    telefone: "(11) 93210-9876",
    cargo: "Chaveiro",
    salario: 2500.0,
    dataAdmissao: "2023-08-20",
    ativo: true,
  },
]

export const vendasMock: Venda[] = [
  {
    id: "1",
    data: "2024-11-12T09:30:00",
    clienteId: "1",
    clienteNome: "João Silva",
    funcionarioId: "2",
    funcionarioNome: "Ana Costa",
    itens: [
      {
        tipo: "produto",
        id: "1",
        nome: "Cópia de Chave Simples",
        preco: 15.0,
        quantidade: 3,
        subtotal: 45.0,
      },
    ],
    subtotal: 45.0,
    desconto: 0,
    total: 45.0,
    formaPagamento: "dinheiro",
    status: "concluida",
  },
  {
    id: "2",
    data: "2024-11-12T10:15:00",
    funcionarioId: "3",
    funcionarioNome: "Pedro Lima",
    itens: [
      {
        tipo: "servico",
        id: "1",
        nome: "Abertura de Porta",
        preco: 120.0,
        quantidade: 1,
        subtotal: 120.0,
      },
    ],
    subtotal: 120.0,
    desconto: 0,
    total: 120.0,
    formaPagamento: "pix",
    status: "concluida",
  },
  {
    id: "3",
    data: "2024-11-12T11:00:00",
    clienteId: "2",
    clienteNome: "Maria Santos",
    funcionarioId: "2",
    funcionarioNome: "Ana Costa",
    itens: [
      {
        tipo: "produto",
        id: "2",
        nome: "Cópia de Chave Tetra",
        preco: 25.0,
        quantidade: 2,
        subtotal: 50.0,
      },
      {
        tipo: "produto",
        id: "3",
        nome: "Controle Remoto Universal",
        preco: 80.0,
        quantidade: 1,
        subtotal: 80.0,
      },
    ],
    subtotal: 130.0,
    desconto: 10.0,
    total: 120.0,
    formaPagamento: "cartao_credito",
    status: "concluida",
  },
]

export const caixaAtualMock: Caixa = {
  id: "1",
  dataAbertura: "2024-11-12T08:00:00",
  funcionarioAberturaId: "1",
  funcionarioAberturaNome: "Roberto Souza",
  valorAbertura: 200.0,
  status: "aberto",
  movimentacoes: [
    {
      id: "1",
      data: "2024-11-12T08:00:00",
      tipo: "entrada",
      categoria: "suprimento",
      valor: 200.0,
      descricao: "Abertura de caixa",
      funcionarioId: "1",
      funcionarioNome: "Roberto Souza",
    },
    {
      id: "2",
      data: "2024-11-12T09:30:00",
      tipo: "entrada",
      categoria: "venda",
      valor: 45.0,
      descricao: "Venda #1",
      funcionarioId: "2",
      funcionarioNome: "Ana Costa",
      vendaId: "1",
    },
    {
      id: "3",
      data: "2024-11-12T10:15:00",
      tipo: "entrada",
      categoria: "venda",
      valor: 120.0,
      descricao: "Venda #2",
      funcionarioId: "3",
      funcionarioNome: "Pedro Lima",
      vendaId: "2",
    },
    {
      id: "4",
      data: "2024-11-12T11:00:00",
      tipo: "entrada",
      categoria: "venda",
      valor: 120.0,
      descricao: "Venda #3",
      funcionarioId: "2",
      funcionarioNome: "Ana Costa",
      vendaId: "3",
    },
  ],
}

export const categoriasDespesasMock: CategoriaDespesa[] = [
  { id: "1", nome: "Aluguel", cor: "#3b82f6", ativo: true },
  { id: "2", nome: "Água", cor: "#06b6d4", ativo: true },
  { id: "3", nome: "Energia", cor: "#f59e0b", ativo: true },
  { id: "4", nome: "Internet", cor: "#8b5cf6", ativo: true },
  { id: "5", nome: "Fornecedores", cor: "#10b981", ativo: true },
  { id: "6", nome: "Salários", cor: "#ef4444", ativo: true },
  { id: "7", nome: "Manutenção", cor: "#f97316", ativo: true },
  { id: "8", nome: "Marketing", cor: "#ec4899", ativo: true },
  { id: "9", nome: "Outras Despesas", cor: "#6b7280", ativo: true },
]

export const contasPagarMock: ContaPagar[] = [
  {
    id: "1",
    descricao: "Aluguel da Loja - Novembro",
    valor: 2500.0,
    dataVencimento: "2024-11-15",
    categoriaId: "1",
    categoria: "Aluguel",
    status: "pendente",
    recorrente: true,
  },
  {
    id: "2",
    descricao: "Conta de Água - Outubro",
    valor: 150.0,
    dataVencimento: "2024-11-10",
    dataPagamento: "2024-11-09",
    categoriaId: "2",
    categoria: "Água",
    status: "paga",
    recorrente: true,
  },
  {
    id: "3",
    descricao: "Fornecedor de Chaves - Lote Novembro",
    valor: 1200.0,
    dataVencimento: "2024-11-18",
    categoriaId: "5",
    categoria: "Fornecedores",
    status: "pendente",
    recorrente: false,
  },
  {
    id: "4",
    descricao: "Energia Elétrica - Outubro",
    valor: 380.0,
    dataVencimento: "2024-11-08",
    categoriaId: "3",
    categoria: "Energia",
    status: "atrasada",
    recorrente: true,
  },
]

export const contasReceberMock: ContaReceber[] = [
  {
    id: "1",
    descricao: "Serviço de chaveiro - Condomínio Solar",
    valor: 450.0,
    dataVencimento: "2024-11-20",
    clienteId: "1",
    clienteNome: "João Silva",
    status: "pendente",
  },
  {
    id: "2",
    descricao: "Venda de controles - Empresa XYZ",
    valor: 680.0,
    dataVencimento: "2024-11-12",
    dataRecebimento: "2024-11-11",
    clienteId: "2",
    clienteNome: "Maria Santos",
    status: "recebida",
  },
  {
    id: "3",
    descricao: "Instalação de fechaduras - Edifício Centro",
    valor: 1200.0,
    dataVencimento: "2024-11-05",
    clienteId: "3",
    clienteNome: "Carlos Oliveira",
    status: "atrasada",
  },
]

export const vendasPrazoMock: VendaPrazo[] = [
  {
    id: "1",
    vendaId: "VND-001",
    clienteId: "1",
    clienteNome: "João Silva",
    valorTotal: 600.0,
    valorPago: 200.0,
    valorRestante: 400.0,
    dataVenda: "2024-11-01",
    dataVencimento: "2024-12-01",
    status: "parcial",
    parcelas: [
      {
        id: "1",
        numero: 1,
        valor: 200.0,
        dataVencimento: "2024-11-10",
        dataPagamento: "2024-11-09",
        status: "paga",
      },
      {
        id: "2",
        numero: 2,
        valor: 200.0,
        dataVencimento: "2024-11-25",
        status: "pendente",
      },
      {
        id: "3",
        numero: 3,
        valor: 200.0,
        dataVencimento: "2024-12-10",
        status: "pendente",
      },
    ],
  },
  {
    id: "2",
    vendaId: "VND-002",
    clienteId: "2",
    clienteNome: "Maria Santos",
    valorTotal: 300.0,
    valorPago: 0,
    valorRestante: 300.0,
    dataVenda: "2024-11-05",
    dataVencimento: "2024-11-20",
    status: "pendente",
    parcelas: [
      {
        id: "4",
        numero: 1,
        valor: 300.0,
        dataVencimento: "2024-11-20",
        status: "pendente",
      },
    ],
  },
]

export const perdasMock: Perda[] = [
  {
    id: "1",
    produtoId: "1",
    produtoNome: "Cópia de Chave Simples",
    quantidade: 2,
    custoUnitario: 5.0,
    custoTotal: 10.0,
    funcionarioId: "2",
    funcionarioNome: "Ana Costa",
    categoriaId: "1",
    categoria: "Quebra durante confecção",
    motivo: "Quebra durante confecção",
    data: "2024-11-10T14:30:00",
    observacoes: "Chave quebrou no processo de corte",
  },
  {
    id: "2",
    produtoId: "2",
    produtoNome: "Cópia de Chave Tetra",
    quantidade: 1,
    custoUnitario: 10.0,
    custoTotal: 10.0,
    funcionarioId: "3",
    funcionarioNome: "Pedro Lima",
    categoriaId: "2",
    categoria: "Erro de confecção",
    motivo: "Erro de confecção",
    data: "2024-11-08T10:15:00",
    observacoes: "Erro no código da chave",
  },
]

export const categoriasPerdasMock: CategoriaPerda[] = [
  { id: "1", nome: "Quebra durante confecção", cor: "#f59e0b", ativo: true },
  { id: "2", nome: "Erro de confecção", cor: "#ef4444", ativo: true },
  { id: "3", nome: "Produto danificado", cor: "#f97316", ativo: true },
  { id: "4", nome: "Erro de corte", cor: "#dc2626", ativo: true },
  { id: "5", nome: "Defeito de fabricação", cor: "#ea580c", ativo: true },
  { id: "6", nome: "Outros", cor: "#6b7280", ativo: true },
]
